---
- name: Build list of all packages
  set_fact:
    apt_packages: "{{ deb_packages_general + deb_packages_specific }}"

- name: Print out list of apt packages
  debug:
    msg: "{{ apt_packages }}"
  run_once: true

- name: Install software using apt
  when: ansible_os_family == 'Debian'
  apt:
    pkg: "{{ apt_packages }}"
  become: true
