- name: Ensure nfs-kernel-server is installed
  when: ansible_os_family == 'Debian'
  apt:
    pkg: nfs-kernel-server
  become: true

- name: Template /etc/exports
  ansible.builtin.template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: root
    group: root
    mode: '0644'
  become: true


- name: Restart nfs-kernel-server service
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
  become: true
