# https://pve.proxmox.com/wiki/Package_Repositories

- name: Template /etc/apt.sources.list.d config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/sources.list.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  with_items:
    - debian.sources
    - ceph.sources
    - pve-community.sources

- name: Ensure enterprise repo configuration is absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/pve-enterprise.list"
    - "/etc/apt/sources.list.d/pve-enterprise.sources"
