- name: Configure sshd
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    append_newline: true
    prepend_newline: true
    block: |
      PasswordAuthentication no

- name: Restart sshd service
  ansible.builtin.service:
    name: sshd
    state: restarted
